### ISSUE TITLE
Generation of client with yaml from swagger ui dont validate Spec

### ISSUE THREAD

**Issue by yodatak** [Phalcode/gamevault-backend#146]
Download https://demo.gamevau.lt/api/docs-yaml
then try to generate a client with this command

sudo npx @openapitools/openapi-generator-cli generate -i test.yaml -g rust -o /tmp/test2/ 
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 0
Errors: 
	-attribute components.schemas.Game.items is missing

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:620)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:647)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:479)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)

**Comment by Alfagun74** [comment]
Thanks, will be fixed in 2.2.0

**Comment by Alfagun74** [comment]
https://github.com/Phalcode/gamevault-backend/commit/b71c9c0ccef516586a3b1edf1a50f063fe5264a0

**Comment by yodatak** [comment]
with latest 3.0 i got also the problem (different) 

sudo npx @openapitools/openapi-generator-cli generate -i docs-yaml -g rust -o /tmp/test2/                                                                                                                                                                                                                       
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 8, Warning count: 0
Errors: 
	-attribute components.schemas.Genre.items is missing
	-attribute components.schemas.Publisher.items is missing
	-attribute info.version is missing
	-attribute components.schemas.GamevaultUser.items is missing
	-attribute components.schemas.Developer.items is missing
	-attribute components.schemas.Store.items is missing
	-attribute components.schemas.Game.items is missing
	-attribute components.schemas.Tag.items is missing

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:620)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:647)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:479)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)


we must validate the spec automaticly in the CI/CD i think 

to reproduce in fedora
sudo dnf install nodejs java
and then 
sudo npx @openapitools/openapi-generator-cli generate -i https://demo.gamevau.lt/api/docs-yaml -g bash -o /tmp/test2/                                                                                                                                                                                            
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 8, Warning count: 0
Errors: 
	-attribute components.schemas.Genre.items is missing
	-attribute components.schemas.Publisher.items is missing
	-attribute info.version is missing
	-attribute components.schemas.GamevaultUser.items is missing
	-attribute components.schemas.Developer.items is missing
	-attribute components.schemas.Store.items is missing
	-attribute components.schemas.Game.items is missing
	-attribute components.schemas.Tag.items is missing

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:620)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:647)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:479)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)

**Comment by yodatak** [comment]
@Alfagun74  its not fixed :/

**Comment by Alfagun74** [comment]
damn, i double checked actually. Let me see what i can do.

**Comment by Alfagun74** [comment]
fixed in v4.0.0, the next version, sorry again.

**Comment by yodatak** [comment]
thanks i want to do a simple cli to download some games and maybe looking how to do a client but i'm not a dev :/

**Comment by yodatak** [comment]
sorry to bother you again but again the spec are not valid

npx @openapitools/openapi-generator-cli generate -i https://games.XXXXX.fr/api/docs-yaml -g typescript -o typescript-gamevault 
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 0
Errors: 
	-attribute paths.'/api/v1/health/admin'(get).operationId is repeated

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:668)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:695)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:503)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)

**Comment by yodatak** [comment]
I don't know how to but some github workflow will help 
https://swagger.io/blog/api-design/validate-openapi-definitions-swagger-editor/

**Comment by Alfagun74** [comment]
fixed, if you want automatic validation, id be happy to accept a pr
