### ISSUE TITLE
GameVault server not processing some game titles.

### ISSUE THREAD

**Issue by Wh1t3Rose** [Phalcode/gamevault-backend#159]
**Describe the bug**
GameVault server not processing some game titles.

**To Reproduce**
7zip game like so `7z a "Hades (v1.38246).7z" "C:\GameVault\Packages\Hades (v1.38246)\*\"`
Upload .7z file to game server for processing
Error appears in log

Error Log:
```
error:   ┃ [10]   timestamp: '2023-07-29T22:40:00.109Z'
error:   ┗ [11] }
error:   ┏ Cannot read properties of null (reading '1') +0ms
error:   ┃ [ 1] [Failed to index "Rimworld (v1.4).7z". Does this file really belong here and are you sure the format is correct?"]
error:   ┃ [ 2] {
error:   ┃ [ 3]   context: 'FilesService',
error:   ┃ [ 4]   error: TypeError: Cannot read properties of null (reading '1')
error:   ┃ [ 5]       at FilesService.regexExtractReleaseYear (/app/dist/services/files.service.js:101:52)
error:   ┃ [ 6]       at FilesService.indexFiles (/app/dist/services/files.service.js:40:58)
error:   ┃ [ 7]       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error:   ┃ [ 8]       at async AutomationService.autoindexGames (/app/dist/services/automation.service.js:99:9)
error:   ┃ [ 9]       at async CJ.<anonymous> (/app/node_modules/.pnpm/@nestjs+schedule@3.0.1_@nestjs+common@10.0.5_@nestjs+core@10.0.5_reflect-metadata@0.1.13/node_modules/@nestjs/schedule/dist/schedule.explorer.js:88:17),
```

**Comment by Alfagun74** [comment]
Not a bug, theres no release year in your files title. See https://gamevau.lt/docs/server-docs/structure#:~:text=(EA)-,ReleaseYear,-The%20year%20of.

**Comment by Wh1t3Rose** [comment]
Oh I didn't realize it was actually REQUIRED. I thought it was optional. I suggest making that more clear in the guide

**Comment by Alfagun74** [comment]
thank you for the heads up
