### ISSUE TITLE
What on earth do I do here?

### ISSUE THREAD

**Issue by techsideofficial** [Phalcode/gamevault-backend#225]
```
/home/wienerwolf77/gamevault-backend/node_modules/.pnpm/better-sqlite3@9.0.0/node_modules/better-sqlite3/lib/methods/wrappers.js:5
        return this[cppdb].prepare(sql, this, false);
                    ^
SqliteError: no such table: game
    at Database.prepare (/home/wienerwolf77/gamevault-backend/node_modules/.pnpm/better-sqlite3@9.0.0/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at BetterSqlite3QueryRunner.getStmt (/home/wienerwolf77/gamevault-backend/node_modules/.pnpm/typeorm@0.3.17_better-sqlite3@9.0.0_pg@8.11.3_ts-node@10.9.1/node_modules/typeorm/src/driver/better-sqlite3/BetterSqlite3QueryRunner.ts:44:43)
    at async BetterSqlite3QueryRunner.query (/home/wienerwolf77/gamevault-backend/node_modules/.pnpm/typeorm@0.3.17_better-sqlite3@9.0.0_pg@8.11.3_ts-node@10.9.1/node_modules/typeorm/src/driver/better-sqlite3/BetterSqlite3QueryRunner.ts:89:22)
    at async SelectQueryBuilder.loadRawResults (/home/wienerwolf77/gamevault-backend/node_modules/.pnpm/typeorm@0.3.17_better-sqlite3@9.0.0_pg@8.11.3_ts-node@10.9.1/node_modules/src/query-builder/SelectQueryBuilder.ts:3789:25)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/home/wienerwolf77/gamevault-backend/node_modules/.pnpm/typeorm@0.3.17_better-sqlite3@9.0.0_pg@8.11.3_ts-node@10.9.1/node_modules/src/query-builder/SelectQueryBuilder.ts:3541:26)
    at async SelectQueryBuilder.getRawAndEntities (/home/wienerwolf77/gamevault-backend/node_modules/.pnpm/typeorm@0.3.17_better-sqlite3@9.0.0_pg@8.11.3_ts-node@10.9.1/node_modules/src/query-builder/SelectQueryBuilder.ts:1670:29)
    at async SelectQueryBuilder.getMany (/home/wienerwolf77/gamevault-backend/node_modules/.pnpm/typeorm@0.3.17_better-sqlite3@9.0.0_pg@8.11.3_ts-node@10.9.1/node_modules/src/query-builder/SelectQueryBuilder.ts:1760:25)
```

**Comment by Alfagun74** [comment]
I can't figure out the problem because I don't have enough information. Please share all the details, like when it happens, what you do, and how you're doing it.

**Comment by techsideofficial** [comment]
> I can't figure out the problem because I don't have enough information. Please share all the details, like the FULL log, when it happens, what you do, and how you're doing it.

```
wienerwolf77@instance-1:~$ cd gamevault-backend/dist/src
wienerwolf77@instance-1:~/gamevault-backend/dist/src$ node main
info:    ┏ Starting Nest application... +0ms
info:    ┗ [1] { context: 'NestFactory', timestamp: '2023-12-12T22:31:11.420Z' }
info:    ┏ TypeOrmModule dependencies initialized +101ms
info:    ┗ [1] { context: 'InstanceLoader', timestamp: '2023-12-12T22:31:11.619Z' }
```

That is the full log. I am using the native approach, because I am doing it on a Google Cloud VM.
