### ISSUE TITLE
"No Box Available" for entire library of games.

### ISSUE THREAD

**Issue by Markovski2338** [Phalcode/gamevault-backend#308]
Looks like pulling Box pictures for all games is broken. Pulling background pictures works and all game info works too! 

![image](https://github.com/user-attachments/assets/0d7970d2-5521-4861-9341-8d6d014765d4)

![image](https://github.com/user-attachments/assets/078e914a-928d-4dd7-a2e7-89ac9c984a89)

**Comment by Alfagun74** [comment]
Hi @Markovski2338, 

this is a known issue and there is no fix for the time except for setting the boxarts yourself.

The First Problem: Rawg doesnt deliver Box Images. They only deliver Backgrounds. Thus we used a scraper to scrape Images off of Google.

The Second Problem: Both RAWG and Google Images are very unreliable Sources. They don't deliver data reliably.

The Solution: Wait. There is a **massive** update just around the corner. [Currently in early access phase if you want to participate](https://gamevau.lt/docs/advanced-usage/early-access-program), that completely scraps RAWG and Google Images and introduces a brand new metadata framework with built-in IGDB support. Then Both the data and images will work perfectly flawless.

**Comment by cherryontopknife** [comment]
I experience this issue. I don't see anything in my logs about the server attempting to match/ map games and grab the art.

**Comment by cherryontopknife** [comment]
Ah, if I restart the server it spits out a big error stack. Looks like too many requests

```
(0,4,6,7,8,9,10,11,12);","env":{},"headers":{"Accept":"application/json, text/plain, */*","Accept-Encoding":"gzip, compress, deflate, br","Content-Length":"132","Content-Type":"application/x-www-form-urlencoded","User-Agent":"axios/1.7.7","authorization":"Bearer u9hw145cfwse08skuai6bjnw9y8m84","client-id":"prixpjwicttzf5vjeyz71cxwqkfd2q"},"maxBodyLength":-1,"maxContentLength":-1,"method":"post","queryMethod":"body","timeout":0,"transformRequest":[null],"transformResponse":[null],"transitional":{"clarifyTimeoutError":false,"forcedJSONParsing":true,"silentJSONParsing":true},"url":"https://api.igdb.com/v4/games","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN"},"message":"Request failed with status code 429","name":"AxiosError","stack":"AxiosError: Request failed with status code 429\n    at settle (/app/node_modules/.pnpm/axios@1.7.7/node_modules/axios/dist/node/axios.cjs:2019:12)\n    at IncomingMessage.handleStreamEnd (/app/node_modules/.pnpm/axios@1.7.7/node_modules/axios/dist/node/axios.cjs:3135:11)\n    at IncomingMessage.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (/app/node_modules/.pnpm/axios@1.7.7/node_modules/axios/dist/node/axios.cjs:4287:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async IgdbMetadataProviderService.search (/app/dist/src/modules/metadata/providers/igdb/igdb.metadata-provider.service.js:67:30)\n    at async IgdbMetadataProviderService.getBestMatch (/app/dist/src/modules/metadata/providers/abstract.metadata-provider.service.js:57:29)\n    at async MetadataService.findMetadata (/app/dist/src/modules/metadata/metadata.service.js:180:38)\n    at async MetadataService.updateMetadata (/app/dist/src/modules/metadata/metadata.service.js:143:21)\n    at async MetadataService.addUpdateMetadataJob (/app/dist/src/modules/metadata/metadata.service.js:83:13)","status":429},"game":{"file_path":"/files/game-caves.of.qud/setup_caves_of_qud_pets_pack_2.0.209.43_(78617).exe","id":319,"title":"setup_caves_of_qud_pets_pack_2.0.209.43_"},"level":"error","message":"Failed updating metadata for game and provider. Skipping.","ms":"+15ms","provider":{"enabled":true,"priority":10,"request_interval_ms":250,"slug":"igdb"},"stack":[null],"timestamp":"2025-02-12T17:13:05.572Z"}
{"context":"MetadataService","game":319,"level":"warn","message":"No metadata found to merge.","ms":"+12ms","timestamp":"2025-02-12T17:13:05.584Z"}
{"context":"MetadataService","error":{"code":"ERR_BAD_REQUEST","config":{"adapter":["xhr","http","fetch"],"data":"fields id,name,first_release_date,cover.*;search \"setup_the_dig_1.0_\";where category = (0,4,6,7,8,9,10,11,12);","env":{},"headers":{"Accept":"application/json, text/plain, */*","Accept-Encoding":"gzip, compress, deflate, br","Content-Length":"110","Content-Type":"application/x-www-form-urlencoded","User-Agent":"axios/1.7.7","authorization":"Bearer 6a3lkqsi6gcw6pm03vxatnz8ui8kki","client-id":"prixpjwicttzf5vjeyz71cxwqkfd2q"},"maxBodyLength":-1,"maxContentLength":-1,"method":"post","queryMethod":"body","timeout":0,"transformRequest":[null],"transformResponse":[null],"transitional":{"clarifyTimeoutError":false,"forcedJSONParsing":true,"silentJSONParsing":true},"url":"https://api.igdb.com/v4/games","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN"},"message":"Request failed with status code 429","name":"AxiosError","stack":"AxiosError: Request failed with status code 429\n    at settle (/app/node_modules/.pnpm/axios@1.7.7/node_modules/axios/dist/node/axios.cjs:2019:12)\n    at IncomingMessage.handleStreamEnd (/app/node_modules/.pnpm/axios@1.7.7/node_modules/axios/dist/node/axios.cjs:3135:11)\n    at IncomingMessage.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (/app/node_modules/.pnpm/axios@1.7.7/node_modules/axios/dist/node/axios.cjs:4287:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async IgdbMetadataProviderService.search (/app/dist/src/modules/metadata/providers/igdb/igdb.metadata-provider.service.js:67:30)\n    at async IgdbMetadataProviderService.getBestMatch (/app/dist/src/modules/metadata/providers/abstract.metadata-provider.service.js:57:29)\n    at async MetadataService.findMetadata (/app/dist/src/modules/metadata/metadata.service.js:180:38)\n    at async MetadataService.updateMetadata (/app/dist/src/modules/metadata/metadata.service.js:143:21)\n    at async MetadataService.addUpdateMetadataJob (/app/dist/src/modules/metadata/metadata.service.js:83:13)","status":429},"game":{"file_path":"/files/game-the.dig-(20270)/setup_the_dig_1.0_(20270).exe","id":222,"title":"setup_the_dig_1.0_"},"level":"error","message":"Failed updating metadata for game and provider. Skipping.","ms":"+22ms","provider":{"enabled":true,"priority":10,"request_interval_ms":250,"slug":"igdb"},"stack":[null],"timestamp":"2025-02-12T17:13:05.606Z"}
{"context":"MetadataService","game":222,"level":"warn","message":"No metadata found to merge.","ms":"+12ms","timestamp":"2025-02-12T17:13:05.618Z"}
{"context":"MetadataService","error":{"code":"ERR_BAD_REQUEST","config":{"adapter":["xhr","http","fetch"],"data":"fields id,name,first_release_date,cover.*;search \"setup_carto_1.0.7.6__\";where category = (0,4,6,7,8,9,10,11,12);","env":{},"headers":{"Accept":"application/json, text/plain, */*","Accept-Encoding":"gzip, compress, deflate, br","Content-Length":"113","Content-Type":"application/x-www-form-urlencoded","User-Agent":"axios/1.7.7","authorization":"Bearer em6qk2c35y43nsltpoybczpwnwhc83","client-id":"prixpjwicttzf5vjeyz71cxwqkfd2q"},"maxBodyLength":-1,"maxContentLength":-1,"method":"post","queryMethod":"body","timeout":0,"transformRequest":[null],"transformResponse":[null],"transitional":{"clarifyTimeoutError":false,"forcedJSONParsing":true,"silentJSONParsing":true},"url":"https://api.igdb.com/v4/games","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN"},"message":"Request failed with status code 429","name":"AxiosError","stack":"AxiosError: Request failed with status code 429\n    at settle (/app/node_modules/.pnpm/axios@1.7.7/node_modules/axios/dist/node/axios.cjs:2019:12)\n    at IncomingMessage.handleStreamEnd (/app/node_modules/.pnpm/axios@1.7.7/node_modules/axios/dist/node/axios.cjs:3135:11)\n    at IncomingMessage.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (/app/node_modules/.pnpm/axios@1.7.7/node_modules/axios/dist/node/axios.cjs:4287:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async IgdbMetadataProviderService.search (/app/dist/src/modules/metadata/providers/igdb/igdb.metadata-provider.service.js:67:30)\n    at async IgdbMetadataProviderService.getBestMatch (/app/dist/src/modules/metadata/providers/abstract.metadata-provider.service.js:57:29)\n    at async MetadataService.findMetadata (/app/dist/src/modules/metadata/metadata.service.js:180:38)\n    at async MetadataService.updateMetadata (/app/dist/src/modules/metadata/metadata.service.js:143:21)\n    at async MetadataService.addUpdateMetadataJob (/app/dist/src/modules/metadata/metadata.service.js:83:13)","status":429},"game":{"file_path":"/files/game-carto-(51528)/setup_carto_1.0.7.6_(64bit)_(51528).exe","id":325,"title":"setup_carto_1.0.7.6__"},"level":"error","message":"Failed updating metadata for game and provider. Skipping.","ms":"+68ms","provider":{"enabled":true,"priority":10,"request_interval_ms":250,"slug":"igdb"},"stack":[null],"timestamp":"2025-02-12T17:13:05.686Z"}
{"context":"MetadataService","error":{"code":"ERR_BAD_REQUEST","config":{"adapter":["xhr","http","fetch"],"data":"fields id,name,first_release_date,cover.*;search \"setup_calico_1.0.12_\";where category = (0,4,6,7,8,9,10,11,12);","env":{},"headers":{"Accept":"application/json, text/plain, */*","Accept-Encoding":"gzip, compress, deflate, br","Content-Length":"112","Content-Type":"application/x-www-form-urlencoded","User-Agent":"axios/1.7.7","authorization":"Bearer apl6k4u9o507g33nanv892kyg3fl2j","client-id":"prixpjwicttzf5vjeyz71cxwqkfd2q"},"maxBodyLength":-1,"maxContentLength":-1,"method":"post","queryMethod":"body","timeout":0,"transformRequest":[null],"transformResponse":[null],"transitional":{"clarifyTimeoutError":false,"forcedJSONParsing":true,"silentJSONParsing":true},"url":"https://api.igdb.com/v4/games","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN"},"message":"Request failed with status code 429","name":"AxiosError","stack":"AxiosError: Request failed with status code 429\n    at settle (/app/node_modules/.pnpm/axios@1.7.7/node_modules/axios/dist/node/axios.cjs:2019:12)\n    at IncomingMessage.handleStreamEnd (/app/node_modules/.pnpm/axios@1.7.7/node_modules/axios/dist/node/axios.cjs:3135:11)\n    at IncomingMessage.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (/app/node_modules/.pnpm/axios@1.7.7/node_modules/axios/dist/node/axios.cjs:4287:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async IgdbMetadataProviderService.search (/app/dist/src/modules/metadata/providers/igdb/igdb.metadata-provider.service.js:67:30)\n    at async IgdbMetadataProviderService.getBestMatch (/app/dist/src/modules/metadata/providers/abstract.metadata-provider.service.js:57:29)\n    at async MetadataService.findMetadata (/app/dist/src/modules/metadata/metadata.service.js:180:38)\n    at async MetadataService.updateMetadata (/app/dist/src/modules/metadata/metadata.service.js:143:21)\n    at async MetadataService.addUpdateMetadataJob (/app/dist/src/modules/metadata/metadata.service.js:83:13)","status":429},"game":{"file_path":"/files/game-calico-(48136)/setup_calico_1.0.12_(48136).exe","id":326,"title":"setup_calico_1.0.12_"},"level":"error","message":"Failed updating metadata for game and provider. Skipping.","ms":"+4ms","provider":{"enabled":true,"priority":10,"request_interval_ms":250,"slug":"igdb"},"stack":[null],"timestamp":"2025-02-12T17:13:05.690Z"}
{"context":"MetadataService","game":325,"level":"warn","message":"No metadata found to merge.","ms":"+11ms","timestamp":"2025-02-12T17:13:05.701Z"}
{"context":"MetadataService","game":326,"level":"warn","message":"No metadata found to merge.","ms":"+6ms","timestamp":"2025-02-12T17:13:05.707Z"}
{"context":"MetadataService","error":{"code":"ERR_BAD_REQUEST","config":{"adapter":["xhr","http","fetch"],"data":"fields id,name,first_release_date,cover.*;search \"setup_core_keeper_1.0.1.11-de55__\";where category = (0,4,6,7,8,9,10,11,12);","env":{},"headers":{"Accept":"application/json, text/plain, */*","Accept-Encoding":"gzip, compress, deflate, br","Content-Length":"125","Content-Type":"application/x-www-form-urlencoded","User-Agent":"axios/1.7.7","authorization":"Bearer 498bzit4caakhrst6eyd8rnr6vgybk","client-id":"prixpjwicttzf5vjeyz71cxwqkfd2q"},"maxBodyLength":-1,"maxContentLength":-1,"method":"post","queryMethod":"body","timeout":0,"transformRequest":[null],"transformResponse":[null],"transitional":{"clarifyTimeoutError":false,"forcedJSONParsing":true,"silentJSONParsing":true},"url":"https://api.igdb.com/v4/games","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN"},"message":"Request failed with status code 429","name":"AxiosError","stack":"AxiosError: Request failed with status code 429\n    at settle (/app/node_modules/.pnpm/axios@1.7.7/node_modules/axios/dist/node/axios.cjs:2019:12)\n    at IncomingMessage.handleStreamEnd (/app/node_modules/.pnpm/axios@1.7.7/node_modules/axios/dist/node/axios.cjs:3135:11)\n    at IncomingMessage.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (/app/node_modules/.pnpm/axios@1.7.7/node_modules/axios/dist/node/axios.cjs:4287:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async IgdbMetadataProviderService.search (/app/dist/src/modules/metadata/providers/igdb/igdb.metadata-provider.service.js:67:30)\n    at async IgdbMetadataProviderService.getBestMatch (/app/dist/src/modules/metadata/providers/abstract.metadata-provider.service.js:57:29)\n    at async MetadataService.findMetadata (/app/dist/src/modules/metadata/metadata.service.js:180:38)\n    at async MetadataService.updateMetadata (/app/dist/src/modules/metadata/metadata.service.js:143:21)\n    at async MetadataService.addUpdateMetadataJob (/app/dist/src/modules/metadata/metadata.service.js:83:13)","status":429},"game":{"file_path":"/files/game-core.keeper-(78230)/setup_core_keeper_1.0.1.11-de55_(64bit)_(78230).exe","id":322,"title":"setup_core_keeper_1.0.1.11-de55__"},"level":"error","message":"Failed updating metadata for game and provider. Skipping.","ms":"+22ms","provider":{"enabled":true,"priority":10,"request_interval_ms":250,"slug":"igdb"},"stack":[null],"timestamp":"2025-02-12T17:13:05.729Z"}
{"context":"MetadataService","game":322,"level":"warn","message":"No metadata found to merge.","ms":"+13ms","timestamp":"2025-02-12T17:13:05.742Z"}
{"context":"MetadataService","error":{"code":"ERR_BAD_REQUEST","config":{"adapter":["xhr","http","fetch"],"data":"fields id,name,first_release_date,cover.*;search \"patch_little_big_adventure__twinsens_quest_1.0.4b__to_1.1.2_\";where category = (0,4,6,7,8,9,10,11,12);","env":{},"headers":{"Accept":"application/json, text/plain, */*","Accept-Encoding":"gzip, compress, deflate, br","Content-Length":"152","Content-Type":"application/x-www-form-urlencoded","User-Agent":"axios/1.7.7","authorization":"Bearer 3c1b937y91hn57rvex8cs4nkdomo5e","client-id":"prixpjwicttzf5vjeyz71cxwqkfd2q"},"maxBodyLength":-1,"maxContentLength":-1,"method":"post","queryMethod":"body","timeout":0,"transformRequest":[null],"transformResponse":[null],"transitional":{"clarifyTimeoutError":false,"forcedJSONParsing":true,"silentJSONParsing":true},"url":"https://api.igdb.com/v4/games","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN"},"message":"Request failed with status code 429","name":"AxiosError","stack":"AxiosError: Request failed with status code 429\n    at settle (/app/node_modules/.pnpm/axios@1.7.7/node_modules/axios/dist/node/axios.cjs:2019:12)\n    at IncomingMessage.handleStreamEnd (/app/node_modules/.pnpm/axios@1.7.7/node_modules/axios/dist/node/axios.cjs:3135:11)\n    at IncomingMessage.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (/app/node_modules/.pnpm/axios@1.7.7/node_modules/axios/dist/node/axios.cjs:4287:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async IgdbMetadataProviderService.search (/app/dist/src/modules/metadata/providers/igdb/igdb.metadata-provider.service.js:67:30)\n    at async IgdbMetadataProviderService.getBestMatch (/app/dist/src/modules/metadata/providers/abstract.metadata-provider.service.js:57:29)\n    at async MetadataService.findMetadata (/app/dist/src/modules/metadata/metadata.service.js:180:38)\n    at async MetadataService.updateMetadata (/app/dist/src/modules/metadata/metadata.service.js:143:21)\n    at async MetadataService.addUpdateMetadataJob (/app/dist/src/modules/metadata/metadata.service.js:83:13)","status":429},"game":{"file_path":"/files/game-twinsensquest/patch-fix-other-little.big.adventure.twinsens.quest/patch_little_big_adventure__twinsens_quest_1.0.4b_(77751)_to_1.1.2_(78251).exe","id":205,"title":"patch_little_big_adventure__twinsens_quest_1.0.4b__to_1.1.2_"},"level":"error","message":"Failed updating metadata for game and provider. Skipping.","ms":"+99ms","provider":{"enabled":true,"priority":10,"request_interval_ms":250,"slug":"igdb"},"stack":[null],"timestamp":"2025-02-12T17:13:05.841Z"}
{"context":"MetadataService","game":205,"level":"warn","message":"No metadata found to merge.","ms":"+13ms","timestamp":"2025-02-12T17:13:05.854Z"}
{"context":"MetadataService","error":{"code":"ERR_BAD_REQUEST","config":{"adapter":["xhr","http","fetch"],"data":"fields id,name,first_release_date,cover.*;search \"setup_to_the_moon_17763.475_fix_\";where category = (0,4,6,7,8,9,10,11,12);","env":{},"headers":{"Accept":"application/json, text/plain, */*","Accept-Encoding":"gzip, compress, deflate, br","Content-Length":"124","Content-Type":"application/x-www-form-urlencoded","User-Agent":"axios/1.7.7","authorization":"Bearer 27o6t7kdtn0qlr97e5mhe7xbencp6v","client-id":"prixpjwicttzf5vjeyz71cxwqkfd2q"},"maxBodyLength":-1,"maxContentLength":-1,"method":"post","queryMethod":"body","timeout":0,"transformRequest":[null],"transformResponse":[null],"transitional":{"clarifyTimeoutError":false,"forcedJSONParsing":true,"silentJSONParsing":true},"url":"https://api.igdb.com/v4/games","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN"},"message":"Request failed with status code 429","name":"AxiosError","stack":"AxiosError: Request failed with status code 429\n    at settle (/app/node_modules/.pnpm/axios@1.7.7/node_modules/axios/dist/node/axios.cjs:2019:12)\n    at IncomingMessage.handleStreamEnd (/app/node_modules/.pnpm/axios@1.7.7/node_modules/axios/dist/node/axios.cjs:3135:11)\n    at IncomingMessage.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (/app/node_modules/.pnpm/axios@1.7.7/node_modules/axios/dist/node/axios.cjs:4287:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async IgdbMetadataProviderService.search (/app/dist/src/modules/metadata/providers/igdb/igdb.metadata-provider.service.js:67:30)\n    at async IgdbMetadataProviderService.getBestMatch (/app/dist/src/modules/metadata/providers/abstract.metadata-provider.service.js:57:29)\n    at async MetadataService.findMetadata (/app/dist/src/modules/metadata/metadata.service.js:180:38)\n    at async MetadataService.updateMetadata (/app/dist/src/modules/metadata/metadata.service.js:143:21)\n    at async MetadataService.addUpdateMetadataJob (/app/dist/src/modules/metadata/metadata.service.js:83:13)","status":429},"game":{"file_path":"/files/game-to.the.moon-(29673)/setup_to_the_moon_17763.475_fix_(29673).exe","id":226,"title":"setup_to_the_moon_17763.475_fix_"},"level":"error","message":"Failed updating metadata for game and provider. Skipping.","ms":"+494ms","provider":{"enabled":true,"priority":10,"request_interval_ms":250,"slug":"igdb"},"stack":[null],"timestamp":"2025-02-12T17:13:06.348Z"}
{"context":"MetadataService","game":226,"level":"warn","message":"No metadata found to merge.","ms":"+14ms","timestamp":"2025-02-12T17:13:06.362Z"}
```

**Comment by christorepl** [comment]
It looks like GameVault just makes way too many requests all at once. I didn't locate a setting to change this.

**Comment by Alfagun74** [comment]
You can adjust the METADATA_IGDB_REQUEST_INTERVAL_MS Setting to a higher value like 1250, but the issue will probably fix itself after a couple days of trying.
