### ISSUE TITLE
Gamevault Backend keeps Crashing  "Failed to inject plugins folder."

### ISSUE THREAD

**Issue by D-E-N-U** [Phalcode/gamevault-backend#320]
After Updating to the Latest Docker Version the GameVault-Backend keeps crashing and restarting itself

**To Reproduce**
1. Pull GameVault-Backend Docker with sqlitedb (From Unraid App Section) (13.0.4)
2. Populate mandatory Variables
3. Start Container

![image](https://github.com/user-attachments/assets/d6a722c7-57e9-4ca2-b837-77d98d7f24a7)

```
error:   ┏ Failed to inject plugins folder. +0ms
error:   ┃ [ 1] []
error:   ┃ [ 2] {
error:   ┃ [ 3]   context: 'PluginLoader',
error:   ┃ [ 4]   error: Error: EACCES: permission denied, mkdir '/app/dist/src/../plugins'
error:   ┃ [ 5]       at async mkdir (node:internal/fs/promises:858:10)
error:   ┃ [ 6]       at async checkParentDir (node:internal/fs/cp/cp:143:3)
error:   ┃ [ 7]       at async injectPluginFolder (/app/src/plugin.ts:92:5)
error:   ┃ [ 8]       at async loadPlugins (/app/src/plugin.ts:25:5)
error:   ┃ [ 9]       at async bootstrap (/app/src/main.ts:29:25) {
error:   ┃ [10]     code: 'EACCES',
error:   ┃ [11]     errno: -13,
error:   ┃ [12]     path: '/app/dist/src/../plugins',
error:   ┃ [13]     syscall: 'mkdir'
error:   ┃ [14]   },
error:   ┃ [15]   timestamp: '2024-10-25T16:39:58.119Z'
error:   ┗ [16] }
error:   ┏ A fatal error occured +24ms
error:   ┃ [ 1] []
error:   ┃ [ 2] {
error:   ┃ [ 3]   context: undefined,
error:   ┃ [ 4]   error: Error: EACCES: permission denied, mkdir '/app/dist/src/../plugins'
error:   ┃ [ 5]       at async mkdir (node:internal/fs/promises:858:10)
error:   ┃ [ 6]       at async checkParentDir (node:internal/fs/cp/cp:143:3)
error:   ┃ [ 7]       at async injectPluginFolder (/app/src/plugin.ts:92:5)
error:   ┃ [ 8]       at async loadPlugins (/app/src/plugin.ts:25:5)
error:   ┃ [ 9]       at async bootstrap (/app/src/main.ts:29:25) {
error:   ┃ [10]     code: 'EACCES',
error:   ┃ [11]     errno: -13,
error:   ┃ [12]     path: '/app/dist/src/../plugins',
error:   ┃ [13]     syscall: 'mkdir'
error:   ┃ [14]   },
error:   ┃ [15]   timestamp: '2024-10-25T16:39:58.144Z'
error:   ┗ [16] }
```

**Comment by Alfagun74** [comment]
Should be fixed in 13.1.0 now., so sorry about that.
